name: build
on:
  push:
    branches:
      - master
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-dotnet@v5
        with:
          dotnet-version: 10.0.x
      - run: dotnet build Hto3.StringHelpers/Hto3.StringHelpers.csproj --configuration Release
  test:
    name: Test
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-dotnet@v5
        with:
          dotnet-version: 10.0.x
      - run: dotnet test -f net10.0 /p:CollectCoverage=true /p:CoverletOutputFormat=lcov
      - run: curl -s https://codecov.io/bash > codecov
      - run: chmod +x codecov
      - run: ./codecov -f "Hto3.StringHelpers.Test/coverage.info" -t ${{secrets.CODECOV_UPLOAD_TOKEN}}
  publish:
    name: Nuget Publish
    runs-on: windows-latest
    needs: test
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-dotnet@v5
        with:
          dotnet-version: 10.0.x
      - run: dotnet build -c Release Hto3.StringHelpers/Hto3.StringHelpers.csproj
      - run: dotnet pack --no-build -c Release Hto3.StringHelpers/Hto3.StringHelpers.csproj -o .
      - run: dotnet nuget push *.nupkg -s https://api.nuget.org/v3/index.json -k ${{secrets.NUGET_API_KEY}} --skip-duplicate -n
